INSERT INTO TB_USER (USER_ID, USER_NM, ACV) VALUES ('ID1', 'NAME1', 'Y');
INSERT INTO TB_USER (USER_ID, USER_NM, ACV) VALUES ('ID2', 'NAME2', 'Y');
INSERT INTO TB_USER (USER_ID, USER_NM, ACV) VALUES ('ID3', 'NAME3', 'N');
INSERT INTO TB_USER (USER_ID, USER_NM, ACV) VALUES ('ID4', 'NAME4', 'Y');
INSERT INTO TB_USER (USER_ID, USER_NM, ACV) VALUES ('ID5', 'NAME5', 'Y');

INSERT INTO TB_ORG (ORG_CD, ORG_NM, ACV, PREN_ORG_CD) VALUES ('ORGCD1', 'ORG1', 'Y', NULL);
INSERT INTO TB_ORG (ORG_CD, ORG_NM, ACV, PREN_ORG_CD) VALUES ('ORGCD2', 'ORG2', 'Y', 'ORGCD1');
INSERT INTO TB_ORG (ORG_CD, ORG_NM, ACV, PREN_ORG_CD) VALUES ('ORGCD3', 'ORG3', 'Y', 'ORGCD2');
INSERT INTO TB_ORG (ORG_CD, ORG_NM, ACV, PREN_ORG_CD) VALUES ('ORGCD4', 'ORG4', 'N', NULL);

INSERT INTO TB_ORG_USERS (ORG_CD, USER_ID) VALUES ('ORGCD1', 'ID1');
INSERT INTO TB_ORG_USERS (ORG_CD, USER_ID) VALUES ('ORGCD2', 'ID2');
INSERT INTO TB_ORG_USERS (ORG_CD, USER_ID) VALUES ('ORGCD2', 'ID3');
INSERT INTO TB_ORG_USERS (ORG_CD, USER_ID) VALUES ('ORGCD3', 'ID4');
INSERT INTO TB_ORG_USERS (ORG_CD, USER_ID) VALUES ('ORGCD3', 'ID5');



